function groupByStatus(findings, status) {
  return findings.filter((finding) => finding.status === status);
}

function humanEngineLabel(engine) {
  return engine === 'google' ? 'Google' : engine === 'yandex' ? 'Yandex' : engine;
}

function renderFindingsTable(findings) {
  if (findings.length === 0) {
    return '| Status | Finding | Details | Recommendation |\n|---|---|---|---|\n| N/A | No findings | No applicable checks were produced. |  |\n';
  }

  const rows = findings.map((finding) => {
    const engines = finding.engines?.length ? ` [${finding.engines.map(humanEngineLabel).join(', ')}]` : '';
    return `| ${finding.status} | ${finding.title}${engines} | ${String(finding.details || '').replace(/\|/g, '\\|')} | ${String(
      finding.recommendation || ''
    ).replace(/\|/g, '\\|')} |`;
  });

  return ['| Status | Finding | Details | Recommendation |', '|---|---|---|---|', ...rows].join('\n');
}

export function renderMarkdownReport(auditResult) {
  const { metadata, scores, findings } = auditResult;
  const critical = groupByStatus(findings, 'FAIL');
  const warnings = groupByStatus(findings, 'WARN');
  const positives = groupByStatus(findings, 'PASS');
  const technical = findings.filter((finding) => finding.category === 'technical');
  const onPage = findings.filter((finding) => finding.category === 'on_page');
  const engine = findings.filter((finding) => finding.category === 'engine');
  const performance = findings.filter((finding) => finding.category === 'performance');

  const actionPlan = [...critical, ...warnings].slice(0, 5);
  const engineBreakdown = Object.entries(scores.engines)
    .map(([engineName, engineScore]) => `| ${humanEngineLabel(engineName)} | ${engineScore.score}/100 | ${engineScore.grade} |`)
    .join('\n');

  return `# SEO Audit Report
**URL:** ${metadata.url}
**Date:** ${metadata.generatedAt}
**Tier:** ${metadata.tier}
**Engines:** ${metadata.engines.map(humanEngineLabel).join(', ')}
**Overall Score:** ${scores.overall.score}/100 (${scores.overall.grade})

---

## Executive Summary
This audit crawled ${auditResult.crawlSummary.pagesCrawled} pages and evaluated technical SEO, on-page quality, search-engine-specific signals, and lightweight performance indicators.
The highest-impact priorities are reducing failures in crawl/index signals, resolving duplicate or weak metadata, and tightening the signals that matter specifically to ${metadata.engines.map(humanEngineLabel).join(' + ')}.

## Score Breakdown
| Category | Score | Grade |
|---|---|---|
| Technical SEO | ${scores.categories.technical.score}/100 | ${scores.categories.technical.grade} |
| On-Page SEO | ${scores.categories.on_page.score}/100 | ${scores.categories.on_page.grade} |
| Engine Signals | ${scores.categories.engine.score}/100 | ${scores.categories.engine.grade} |
| Performance | ${scores.categories.performance.score}/100 | ${scores.categories.performance.grade} |
| **Overall** | **${scores.overall.score}/100** | **${scores.overall.grade}** |

## Engine Breakdown
| Engine | Score | Grade |
|---|---|---|
${engineBreakdown || '| N/A | 100/100 | A |'}

## Critical Issues (Fix Immediately)
${critical.length > 0 ? critical.map((finding, index) => `${index + 1}. **${finding.title}**: ${finding.details} ${finding.recommendation}`.trim()).join('\n') : '1. No critical FAIL findings were generated in the current crawl scope.'}

## Warnings (Fix Soon)
${warnings.length > 0 ? warnings.map((finding, index) => `${index + 1}. **${finding.title}**: ${finding.details} ${finding.recommendation}`.trim()).join('\n') : '1. No WARN findings were generated in the current crawl scope.'}

## What You Are Doing Well
${positives.length > 0 ? positives.slice(0, 8).map((finding) => `- ${finding.title}`).join('\n') : '- No PASS findings were generated in the current crawl scope.'}

## Priority Action Plan
${actionPlan.length > 0 ? actionPlan.map((finding, index) => `${index + 1}. ${finding.title} - ${finding.recommendation || finding.details}`).join('\n') : '1. Expand the crawl scope or connect optional data providers to increase audit depth.'}

## Optional Modules
${auditResult.optionalModules.map((module) => `- **${module.name}**: ${module.status} - ${module.details}`).join('\n')}

## Detailed Findings

### Technical SEO
${renderFindingsTable(technical)}

### On-Page SEO
${renderFindingsTable(onPage)}

### Search Engine Signals
${renderFindingsTable(engine)}

### Performance
${renderFindingsTable(performance)}

---
*Generated by IndexLift SEO Auditor*
`;
}
